"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[aws]
disabled = true
symbol = 'ó°¸ '   # nf-md-aws

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ](bold red)'

[cmd_duration]
min_time = 200
format = "ğŸ•™ $duration($style) "

[gcloud]
disabled = true
symbol = 'ó±‡¶ '   # nf-md-google_cloud

[package]
disabled = true
